const { chromium } = require('playwright-core'); const path=require('path');
const EXE='/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
(async()=>{ const b=await chromium.launch({executablePath:EXE,args:['--no-sandbox']});
  const p=await b.newPage(); const errs=[]; p.on('pageerror',e=>errs.push(e.message)); p.on('console',m=>{if(m.type()==='error')errs.push(m.text())});
  await p.goto('file://'+path.resolve(__dirname,'../index.html')); await p.waitForTimeout(300);
  const out=await p.evaluate(()=>{ Store.reset(); Dev.seed(60);
    const A=D().assessments.sort((a,b)=>a.ts-b.ts);
    A.forEach((a,i)=>{ if(i%7===0){ a.noteTags=['skipped injection']; a.sliders.fatigue=Math.min(10,(a.sliders.fatigue||5)+3); } });
    Store.saveNow();
    const tags=Insights.noteTags(); const ins=Insights.compute();
    const noteF=ins.findings.filter(f=>f.pk.startsWith('note_')).slice(0,3).map(f=>`${f.pLabel}→${f.oLabel} r=${f.r} ${f.conf}%`);
    return { recurringTags:tags, noteFindings:noteF, total:ins.findings.length }; });
  console.log(JSON.stringify({errs,out},null,2));
  await b.close(); if(errs.length)process.exit(2);
})();
