const { chromium } = require('playwright-core');
const EXE='/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
(async()=>{ const b=await chromium.launch({executablePath:EXE,args:['--no-sandbox']});
  const p=await b.newPage(); const errs=[];
  p.on('pageerror',e=>errs.push('PAGEERR '+e.message)); p.on('console',m=>{if(m.type()==='error')errs.push(m.text())});
  await p.goto('http://localhost:8099/index.html'); await p.waitForTimeout(600);
  const view=await p.evaluate(()=>document.querySelector('#view').children.length);
  const txt=await p.evaluate(()=>document.body.innerText.slice(0,40).replace(/\n/g,' '));
  console.log(JSON.stringify({servedOverHttp:'localhost:8099', errs, viewChildren:view, text:txt}));
  await b.close();
})();
